name: production-files

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.yaml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.yaml'
  workflow_dispatch:

jobs:
  production-files-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k9
      name: generating files for v25
      with:
        # Required - kibot config file
        config: PCB/schematics-v25-2/kicad/config.kibot.yaml 
        # optional - prefix to output defined in config
        dir: PCB/schematics-v25-2/kicad/fabrication
        # optional - schematic file
        schema: 'PCB/schematics-v25-2/kicad/hamodule.kicad_sch'
        # optional - PCB design file
        board: 'PCB/schematics-v25-2/kicad/hamodule.kicad_pcb'
    - name: upload results for v25
      uses: actions/upload-artifact@v2
      with:
        name: output-4-channels-PCB
        path: PCB/schematics-v25-2/kicad/fabrication