name: production-files

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.yaml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.yaml'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  production-files-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k9
      name: generating files for v26.1
      with:
        # Required - kibot config file
        config: PCB/schematics-v26.1/kicad/kibot-configs/config.kibot.yaml 
        # optional - prefix to output defined in config
        dir: PCB/schematics-v26.1/kicad/fabrication/
        # optional - schematic file
        schema: 'PCB/schematics-v26.1/kicad/hamodule.kicad_sch'
        # optional - PCB design file
        board: 'PCB/schematics-v26.1/kicad/hamodule.kicad_pcb'
    - name: upload results for v26.1
      uses: actions/upload-artifact@v4
      with:
        name: output-4-channels-PCB-v26.1
        path: PCB/schematics-v26.1/kicad/fabrication/